### ISSUE TITLE
Rehash configuration failure results in inability to rehash again

### ISSUE THREAD

**Issue by averynbenson** [Y4kuzi/ProvisionIRCd#10]
**Version:** ProvisionIRCd-3.0-beta

If you have the IRCd running, and make changes to the ircd.conf that would cause for the file to not be complete (i.e.; missing brackets, having extra parameters on a block, incorrect block options) and rehash via IRC (/rehash), the IRCd will note that it is rehashing the file but never throws a confirmation or error, preventing the user from being able to rehash in the future.

**Use Case**

1) Edit the ircd.conf to have the following listen block;
```
listen {
    ip *;
    port 6665,6666,6667;
}
```
2) Save the ircd.conf file while the IRCd is running.
3) Through a IRC client, connect, and /oper up.
4) /rehash

**Actual Result:** 
[info] (config) *** KnownSyntax ([sid233169@hampstead.irccloud.com](mailto:sid233169@hampstead.irccloud.com)) is rehashing the server configuration file...
Rehashed config: /home/ircd/ProvisionIRCd/conf/ircd.conf (Rehashing)

**Expected Result:**
[info] (config) *** KnownSyntax ([sid233169@hampstead.irccloud.com](mailto:sid233169@hampstead.irccloud.com)) is rehashing the server configuration file...
Rehashed config: /home/ircd/ProvisionIRCd/conf/ircd.conf (Rehashing)
[info] (config) *** Configuration failed to load, problems were found.

**Comment by Y4kuzi** [comment]
Fixed.
