### ISSUE TITLE
Cannot join channel #

### ISSUE THREAD

**Issue by KnownSyntax** [Y4kuzi/ProvisionIRCd#3]
When you create a new instance of the ircd (or use the development public server), you cannot join the channel # - there is no error message that is thrown to the user (such as forbidden, not allowed, etc.) which can be confusing if someone doesn’t understand why. 

Steps To Reproduce

1. Start a new instance or join the public server 
2. Try to join the channel #
3. Verify you are not able to join it, no error messages are thrown to the user.

**Comment by Y4kuzi** [comment]
Fixed in 1.4-dev.
